// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuNht2HBplMRvF0Ovx222tj43CmHAKMrA',
    appId: '1:487815781695:web:0b149ab0637fa0d9b0878a',
    messagingSenderId: '487815781695',
    projectId: 'guide-app-d44a4',
    authDomain: 'guide-app-d44a4.firebaseapp.com',
    storageBucket: 'guide-app-d44a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAivUL1mpNU3J2IFQH1Izj3Sv9TUs8FXo8',
    appId: '1:487815781695:android:f17a749ae9f886d2b0878a',
    messagingSenderId: '487815781695',
    projectId: 'guide-app-d44a4',
    storageBucket: 'guide-app-d44a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwbLPf9a6PxzE5xw38vl_2XK7CDKesFek',
    appId: '1:487815781695:ios:dfdfecb6d5f2bb9fb0878a',
    messagingSenderId: '487815781695',
    projectId: 'guide-app-d44a4',
    storageBucket: 'guide-app-d44a4.firebasestorage.app',
    iosBundleId: 'com.example.guideAppPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwbLPf9a6PxzE5xw38vl_2XK7CDKesFek',
    appId: '1:487815781695:ios:dfdfecb6d5f2bb9fb0878a',
    messagingSenderId: '487815781695',
    projectId: 'guide-app-d44a4',
    storageBucket: 'guide-app-d44a4.firebasestorage.app',
    iosBundleId: 'com.example.guideAppPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuNht2HBplMRvF0Ovx222tj43CmHAKMrA',
    appId: '1:487815781695:web:5a4220a7c819331fb0878a',
    messagingSenderId: '487815781695',
    projectId: 'guide-app-d44a4',
    authDomain: 'guide-app-d44a4.firebaseapp.com',
    storageBucket: 'guide-app-d44a4.firebasestorage.app',
  );
}
